const FETCH_ADD_REQUEST = 'FETCH_ADD_REQUEST'
const FETCH_ADD_SUCCESS = 'FETCH_ADD_SUCCESS'
const FETCH_ADD_FAILURE = 'FETCH_ADD_FAILURE'
const FETCH_FIND_REQUEST = 'FETCH_FIND_REQUEST'
const FETCH_FIND_SUCCESS = 'FETCH_FIND_SUCCESS'
const FETCH_FIND_FAILURE = 'FETCH_FIND_FAILURE'
const FETCH_UPDATE_SUCCESS = 'FETCH_UPDATE_SUCCESS'
const FETCH_UPDATE_FAILURE = 'FETCH_UPDATE_FAILURE'
const FETCH_UPDATE_REQUEST = 'FETCH_UPDATE_REQUEST'
const FETCH_DELETE_REQUEST = 'FETCH_DELETE_REQUEST'
const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS'
const FETCH_DELETE_FAILURE = 'FETCH_DELETE_FAILURE'
const CLEAR_RESULT = 'CLEAR_RESULT'
const CHANGE_REQUEST_TYPE = 'CHANGE_REQUEST_TYPE'
const SET_CURRENT_WORD = 'SET_CURRENT_WORD'

const FETCH_LOG_IN = 'FETCH_LOG_IN'
const LOG_OUT = 'LOG_OUT'
const FETCH_SIGN_UP = 'FETCH_SIGN_UP'
const REFRESH_TOKEN = 'REFRESH_TOKEN'
const LOGIN_USER = 'LOGIN_USER'
const FETCH_LOG_OUT = 'FETCH_LOG_OUT'

const LOGIN_LOADING ='LOGIN_LOADING'
const LOGIN_SUCCESS ='LOGIN_SUCCESS'
const LOGIN_FAILURE ='LOGIN_FAILURE'


const FETCH_REQUEST = 'FETCH_REQUEST'
const FETCH_REQUEST_LOADING = 'FETCH_REQUEST_LOADING'
const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE'

export {
  FETCH_ADD_REQUEST,
  FETCH_ADD_SUCCESS,
  FETCH_ADD_FAILURE,
  CLEAR_RESULT,
  CHANGE_REQUEST_TYPE,
  SET_CURRENT_WORD,
  FETCH_FIND_REQUEST,
  FETCH_FIND_SUCCESS,
  FETCH_FIND_FAILURE,
  FETCH_UPDATE_SUCCESS,
  FETCH_UPDATE_FAILURE,
  FETCH_UPDATE_REQUEST,
  FETCH_DELETE_REQUEST,
  FETCH_DELETE_SUCCESS,
  FETCH_DELETE_FAILURE,
  FETCH_LOG_IN,
  LOG_OUT,
  FETCH_LOG_OUT,
  FETCH_SIGN_UP,
  LOGIN_USER,
  REFRESH_TOKEN,
  FETCH_REQUEST,
  FETCH_REQUEST_LOADING,
  FETCH_REQUEST_FAILURE,
  LOGIN_LOADING,
LOGIN_SUCCESS,
LOGIN_FAILURE,
}
