const FETCH_ADD_REQUEST = 'FETCH_ADD_REQUEST'
const FETCH_ADD_SUCCESS = 'FETCH_ADD_SUCCESS'
const FETCH_ADD_FAILURE = 'FETCH_ADD_FAILURE'
const CLEAR_RESULT = 'CLEAR_RESULT'
const CHANGE_REQUEST_TYPE = 'CHANGE_REQUEST_TYPE'
const SET_CURRENT_WORD = 'SET_CURRENT_WORD'

export {
  FETCH_ADD_REQUEST,
  FETCH_ADD_SUCCESS,
  FETCH_ADD_FAILURE,
  CLEAR_RESULT,
  CHANGE_REQUEST_TYPE,
  SET_CURRENT_WORD
}
