const FETCH_ADD_REQUEST = 'FETCH_ADD_REQUEST'
const FETCH_ADD_SUCCESS = 'FETCH_ADD_SUCCESS'
const FETCH_ADD_FAILURE = 'FETCH_ADD_FAILURE'
const FETCH_FIND_REQUEST = 'FETCH_FIND_REQUEST'
const FETCH_FIND_SUCCESS = 'FETCH_FIND_SUCCESS'
const FETCH_FIND_FAILURE = 'FETCH_FIND_FAILURE'
const FETCH_UPDATE_SUCCESS = 'FETCH_UPDATE_SUCCESS'
const FETCH_UPDATE_FAILURE = 'FETCH_UPDATE_FAILURE'
const FETCH_UPDATE_REQUEST = 'FETCH_UPDATE_REQUEST'
const FETCH_DELETE_REQUEST = 'FETCH_DELETE_REQUEST'
const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS'
const FETCH_DELETE_FAILURE = 'FETCH_DELETE_FAILURE'
const CLEAR_RESULT = 'CLEAR_RESULT'
const CHANGE_REQUEST_TYPE = 'CHANGE_REQUEST_TYPE'
const SET_CURRENT_WORD = 'SET_CURRENT_WORD'

export {
  FETCH_ADD_REQUEST,
  FETCH_ADD_SUCCESS,
  FETCH_ADD_FAILURE,
  CLEAR_RESULT,
  CHANGE_REQUEST_TYPE,
  SET_CURRENT_WORD,
  FETCH_FIND_REQUEST,
  FETCH_FIND_SUCCESS,
  FETCH_FIND_FAILURE,
  FETCH_UPDATE_SUCCESS,
  FETCH_UPDATE_FAILURE,
  FETCH_UPDATE_REQUEST,
  FETCH_DELETE_REQUEST,
  FETCH_DELETE_SUCCESS,
  FETCH_DELETE_FAILURE,
}
